import { calculateTrendScore } from "./scoring";
import type { MetricTile, SourceRecord, TrendSignal } from "./types";

const demoSources: SourceRecord[] = [
  {
    id: "src-demo-trends-br",
    title: "Mock snapshot: Creative Center Trends BR",
    kind: "DEMO",
    origin: "DEMO",
    collectedAt: "2026-04-21T08:00:00-03:00",
    market: "BR",
    confidence: "medium",
    evidenceCount: 8,
    coverage: "hashtags, videos e audios em review manual",
    freshness: "snapshot demo de hoje",
    gap: "sem API oficial conectada",
  },
  {
    id: "src-demo-top-ads-us",
    title: "Mock snapshot: US early-signal review",
    kind: "DEMO",
    origin: "DEMO",
    collectedAt: "2026-04-21T08:15:00-03:00",
    market: "US",
    confidence: "low",
    evidenceCount: 4,
    coverage: "formatos e criativos de referencia",
    freshness: "mock controlado",
    gap: "transferencia cultural ainda nao provada",
  },
  {
    id: "src-demo-cml",
    title: "Mock snapshot: Commercial Music Library",
    kind: "DEMO",
    origin: "DEMO",
    collectedAt: "2026-04-21T08:30:00-03:00",
    market: "BR",
    confidence: "medium",
    evidenceCount: 5,
    coverage: "hipoteses de audio licenciavel",
    freshness: "mock controlado",
    gap: "licencas reais pendentes",
  },
  {
    id: "src-demo-creator-watch",
    title: "Mock creator watchlist BR",
    kind: "DEMO",
    origin: "DEMO",
    collectedAt: "2026-04-21T08:45:00-03:00",
    market: "BR",
    confidence: "low",
    evidenceCount: 3,
    coverage: "clusters de creators sem perfis reais",
    freshness: "mock controlado",
    gap: "sem creator IDs reais",
  },
];

const signalSeeds: Array<Omit<TrendSignal, "origin" | "score">> = [
  {
    id: "sig-demo-dance-cuts",
    title: "Demo: danca em 3 cortes com troca de figurino",
    summary:
      "Formato de movimento e transicao com leitura rapida, forte para testar retencao inicial sem depender de audio proprietario.",
    type: "FORMAT",
    market: "BR",
    audience: "Danca feminina, beleza e lifestyle",
    status: "rising",
    priority: "now",
    riskLevel: "low",
    stage: "accelerating",
    strength: 84,
    trendWindow: "24-72h para testar variacoes",
    decision: "Priorizar adaptacao com criativo proprio e audio licenciavel.",
    nextAction: "Criar 3 hooks visuais e medir retencao nos 2 primeiros segundos.",
    saved: true,
    source: demoSources[0],
    tags: ["9:16", "hook visual", "transicao", "dance", "demo"],
    evidence: [
      {
        id: "ev-demo-dance-1",
        title: "Cluster visual de transicao rapida",
        sourceLabel: "Creative Center mock",
        quality: "medium",
        timestamp: "2026-04-21T08:00:00-03:00",
        note: "Evidencia simulada para validar leitura de cluster, nao dado real.",
      },
      {
        id: "ev-demo-dance-2",
        title: "Padrao repetivel em beauty/lifestyle",
        sourceLabel: "Manual review mock",
        quality: "medium",
        timestamp: "2026-04-21T08:06:00-03:00",
        note: "Mostra como a UI vai explicar repetibilidade do formato.",
      },
    ],
    history: [
      { label: "velocidade", value: "+18 demo", tone: "acid" },
      { label: "risco", value: "baixo", tone: "aqua" },
      { label: "janela", value: "72h", tone: "gold" },
    ],
    scoreDrivers: ["fit BR alto", "formato repetivel", "risco baixo"],
    scoreInput: {
      velocity7d: 88,
      acceleration: 82,
      brazilFit: 92,
      usTransferability: 28,
      formatRepeatability: 90,
      creatorSignal: 64,
      audioCommercialUsable: 58,
      revivalStrength: 24,
      evidenceQuality: 66,
      riskPenalty: 4,
    },
  },
  {
    id: "sig-demo-audio-safe",
    title: "Demo: audio comercial com energia funk-pop",
    summary:
      "Hipotese marcada como mock para testar leitura de audios licenciaveis antes da integracao real com biblioteca comercial.",
    type: "AUDIO",
    market: "BR",
    audience: "Criativos de performance e social commerce",
    status: "watch",
    priority: "next",
    riskLevel: "low",
    stage: "proving",
    strength: 72,
    trendWindow: "3-5 dias para validar disponibilidade",
    decision: "Manter como candidato se a licenca for confirmada em fonte oficial.",
    nextAction: "Mapear 2 edicoes sem depender de letra ou audio proprietario.",
    saved: true,
    source: demoSources[2],
    tags: ["audio", "CML-ready", "licenca", "performance", "demo"],
    evidence: [
      {
        id: "ev-demo-audio-1",
        title: "Compatibilidade comercial ainda simulada",
        sourceLabel: "CML mock",
        quality: "medium",
        timestamp: "2026-04-21T08:30:00-03:00",
        note: "A UI diferencia audio promissor de audio confirmado.",
      },
    ],
    history: [
      { label: "licenca", value: "pendente", tone: "gold" },
      { label: "fit BR", value: "alto", tone: "acid" },
      { label: "risco", value: "baixo", tone: "aqua" },
    ],
    scoreDrivers: ["audio comercial", "fit BR", "risco baixo"],
    scoreInput: {
      velocity7d: 70,
      acceleration: 56,
      brazilFit: 82,
      usTransferability: 22,
      formatRepeatability: 72,
      creatorSignal: 36,
      audioCommercialUsable: 94,
      revivalStrength: 18,
      evidenceQuality: 58,
      riskPenalty: 2,
    },
  },
  {
    id: "sig-demo-us-to-br",
    title: "Demo: micro-review honesto antes/depois",
    summary:
      "Sinal dos EUA simulado para validar o radar de traducao cultural, com foco em prova visual e promessa moderada.",
    type: "US_TO_BR",
    market: "US",
    audience: "Early signal para adaptacao BR",
    status: "watch",
    priority: "next",
    riskLevel: "medium",
    stage: "emerging",
    strength: 68,
    trendWindow: "5-10 dias para observar traducao BR",
    decision: "Acompanhar antes de investir; alto potencial se ganhar linguagem local.",
    nextAction: "Criar matriz de adaptacao com 2 referencias BR seguras.",
    saved: false,
    source: demoSources[1],
    tags: ["US", "antes-depois", "review", "adaptacao", "demo"],
    evidence: [
      {
        id: "ev-demo-us-1",
        title: "Formato US com promessa visual curta",
        sourceLabel: "US review mock",
        quality: "low",
        timestamp: "2026-04-21T08:15:00-03:00",
        note: "A transferencia para BR ainda esta marcada como hipotese.",
      },
      {
        id: "ev-demo-us-2",
        title: "Necessita localizacao de linguagem",
        sourceLabel: "Strategy note mock",
        quality: "low",
        timestamp: "2026-04-21T08:18:00-03:00",
        note: "Evita tratar sinal internacional como certeza.",
      },
    ],
    history: [
      { label: "transfer", value: "78", tone: "gold" },
      { label: "fit BR", value: "medio", tone: "violet" },
      { label: "risco", value: "medio", tone: "coral" },
    ],
    scoreDrivers: ["transferencia US", "boa repetibilidade", "evidencia baixa"],
    scoreInput: {
      velocity7d: 64,
      acceleration: 70,
      brazilFit: 58,
      usTransferability: 82,
      formatRepeatability: 76,
      creatorSignal: 52,
      audioCommercialUsable: 42,
      revivalStrength: 34,
      evidenceQuality: 42,
      riskPenalty: 8,
    },
  },
  {
    id: "sig-demo-revival",
    title: "Demo: retorno de formato de comentario-resposta",
    summary:
      "Revival simulado de video-resposta para comentarios, com foco em prova social honesta e contexto visivel.",
    type: "REVIVAL",
    market: "BR",
    audience: "Creators, conteudo educativo e marcas pessoais",
    status: "returning",
    priority: "next",
    riskLevel: "low",
    stage: "revival",
    strength: 76,
    trendWindow: "48h para publicar resposta propria",
    decision: "Usar quando houver comentario real e contexto verificavel.",
    nextAction: "Selecionar pergunta real e montar roteiro de resposta em 3 blocos.",
    saved: true,
    source: demoSources[0],
    tags: ["revival", "comentarios", "BTS", "creator", "demo"],
    evidence: [
      {
        id: "ev-demo-revival-1",
        title: "Padrao retornando apos dormencia",
        sourceLabel: "Revival lab mock",
        quality: "medium",
        timestamp: "2026-04-21T08:08:00-03:00",
        note: "Exibe como a tela vai tratar retorno sem falsa escassez.",
      },
    ],
    history: [
      { label: "dormencia", value: "21d", tone: "violet" },
      { label: "retorno", value: "+12 demo", tone: "acid" },
      { label: "risco", value: "baixo", tone: "aqua" },
    ],
    scoreDrivers: ["revival forte", "baixo risco", "execucao simples"],
    scoreInput: {
      velocity7d: 60,
      acceleration: 54,
      brazilFit: 78,
      usTransferability: 46,
      formatRepeatability: 86,
      creatorSignal: 58,
      audioCommercialUsable: 44,
      revivalStrength: 92,
      evidenceQuality: 56,
      riskPenalty: 4,
    },
  },
  {
    id: "sig-demo-hashtag-grwm",
    title: "Demo: hashtag de rotina arrume-se comigo",
    summary:
      "Cluster de hashtag simulado para estudar estrutura de rotina, preparacao e bastidor sem sugerir prova falsa.",
    type: "HASHTAG",
    market: "BR",
    audience: "Beleza, moda, creators e social commerce",
    status: "rising",
    priority: "watch",
    riskLevel: "medium",
    stage: "proving",
    strength: 66,
    trendWindow: "1 semana para testar nichos adjacentes",
    decision: "Monitorar saturacao antes de transformar em campanha principal.",
    nextAction: "Comparar 3 hashtags adjacentes e evitar claims de resultado.",
    saved: false,
    source: demoSources[0],
    tags: ["hashtag", "rotina", "GRWM", "beleza", "demo"],
    evidence: [
      {
        id: "ev-demo-hashtag-1",
        title: "Cluster de rotina com alta adaptabilidade",
        sourceLabel: "Hashtag mock",
        quality: "medium",
        timestamp: "2026-04-21T08:03:00-03:00",
        note: "Mantem separacao entre tendencia observada e decisao de negocio.",
      },
    ],
    history: [
      { label: "fit", value: "alto", tone: "acid" },
      { label: "saturacao", value: "media", tone: "gold" },
      { label: "risco", value: "medio", tone: "coral" },
    ],
    scoreDrivers: ["fit BR", "saturacao media", "bom contexto"],
    scoreInput: {
      velocity7d: 66,
      acceleration: 52,
      brazilFit: 84,
      usTransferability: 36,
      formatRepeatability: 78,
      creatorSignal: 44,
      audioCommercialUsable: 34,
      revivalStrength: 36,
      evidenceQuality: 54,
      riskPenalty: 10,
    },
  },
  {
    id: "sig-demo-creator-cluster",
    title: "Demo: cluster de creators de danca segura",
    summary:
      "Watchlist ficticia de creators para testar monitoramento por consistencia, formato e sinais de colaboracao.",
    type: "CREATOR",
    market: "BR",
    audience: "Creators de danca, lifestyle e produto visual",
    status: "watch",
    priority: "watch",
    riskLevel: "low",
    stage: "monitor",
    strength: 58,
    trendWindow: "2 semanas para observar consistencia",
    decision: "Salvar como watchlist; nao acionar sem fonte oficial ou permissao.",
    nextAction: "Definir criterios de inclusao antes de adicionar perfis reais.",
    saved: false,
    source: demoSources[3],
    tags: ["creator", "watchlist", "danca", "consistencia", "demo"],
    evidence: [
      {
        id: "ev-demo-creator-1",
        title: "Watchlist sem perfis reais",
        sourceLabel: "Creator watch mock",
        quality: "low",
        timestamp: "2026-04-21T08:45:00-03:00",
        note: "Prepara UX de creator monitoring sem expor pessoas reais.",
      },
    ],
    history: [
      { label: "consist.", value: "media", tone: "gold" },
      { label: "risco", value: "baixo", tone: "aqua" },
      { label: "fonte", value: "mock", tone: "violet" },
    ],
    scoreDrivers: ["watchlist", "baixo risco", "fonte fraca"],
    scoreInput: {
      velocity7d: 48,
      acceleration: 42,
      brazilFit: 70,
      usTransferability: 22,
      formatRepeatability: 68,
      creatorSignal: 82,
      audioCommercialUsable: 36,
      revivalStrength: 22,
      evidenceQuality: 34,
      riskPenalty: 3,
    },
  },
  {
    id: "sig-demo-us-silent-story",
    title: "Demo: storytelling silencioso com legenda forte",
    summary:
      "Formato US simulado de edicao sem fala para avaliar se a estrutura visual traduz para criativos BR.",
    type: "FORMAT",
    market: "US",
    audience: "Early signal para formatos adaptaveis",
    status: "watch",
    priority: "hold",
    riskLevel: "medium",
    stage: "emerging",
    strength: 52,
    trendWindow: "monitorar antes de salvar como prioridade",
    decision: "Nao priorizar ainda; usar apenas como referencia de estrutura.",
    nextAction: "Aguardar evidencia BR ou fonte oficial adicional.",
    saved: false,
    source: demoSources[1],
    tags: ["US", "silent edit", "caption", "estrutura", "demo"],
    evidence: [
      {
        id: "ev-demo-silent-1",
        title: "Estrutura visual promissora, sem prova BR",
        sourceLabel: "US review mock",
        quality: "low",
        timestamp: "2026-04-21T08:22:00-03:00",
        note: "Ajuda a UI a mostrar sinais em espera.",
      },
    ],
    history: [
      { label: "transfer", value: "61", tone: "gold" },
      { label: "prior.", value: "hold", tone: "violet" },
      { label: "risco", value: "medio", tone: "coral" },
    ],
    scoreDrivers: ["early US", "evidencia baixa", "aguardar BR"],
    scoreInput: {
      velocity7d: 46,
      acceleration: 50,
      brazilFit: 46,
      usTransferability: 66,
      formatRepeatability: 72,
      creatorSignal: 38,
      audioCommercialUsable: 58,
      revivalStrength: 20,
      evidenceQuality: 32,
      riskPenalty: 9,
    },
  },
];

export const demoSignals: TrendSignal[] = signalSeeds.map((signal) => ({
  ...signal,
  origin: "DEMO",
  score: calculateTrendScore(signal.scoreInput),
}));

export const commandMetrics: MetricTile[] = [
  { label: "Sinais priorizados", value: "03", delta: "demo/mock", tone: "acid" },
  { label: "BR vs US radar", value: "5/2", delta: "mock mix", tone: "aqua" },
  { label: "Evidencias", value: "09", delta: "nao producao", tone: "gold" },
  { label: "Risco alto", value: "0", delta: "safe mode", tone: "coral" },
];

export const sourceQueue = demoSources;
